CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE,
    parent_id BIGINT REFERENCES categories(id),
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE warehouses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(160) NOT NULL,
    code VARCHAR(40) NOT NULL UNIQUE,
    address VARCHAR(500),
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 4) PRIMARY KEY,
    warehouse_id BIGINT REFERENCES warehouses(id),
    name VARCHAR(160) NOT NULL,
    code VARCHAR(60) NOT NULL UNIQUE,
    is_internal BOOLEAN NOT NULL DEFAULT TRUE,
    is_virtual BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    sku VARCHAR(80) NOT NULL UNIQUE,
    category_id BIGINT REFERENCES categories(id),
    unit_of_measure VARCHAR(30),
    per_unit_cost NUMERIC(19, 4),
    reorder_point INTEGER NOT NULL DEFAULT 0,
    reorder_qty INTEGER NOT NULL DEFAULT 0,
    deleted_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT ck_products_reorder_point CHECK (reorder_point >= 0),
    CONSTRAINT ck_products_reorder_qty CHECK (reorder_qty >= 0),
    CONSTRAINT ck_products_cost CHECK (per_unit_cost IS NULL OR per_unit_cost >= 0)
);

CREATE TABLE stock (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id),
    location_id BIGINT NOT NULL REFERENCES locations(id),
    quantity NUMERIC(19, 4) NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_stock_product_location UNIQUE (product_id, location_id),
    CONSTRAINT ck_stock_quantity CHECK (quantity >= 0)
);

CREATE TABLE stock_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id),
    location_from_id BIGINT NOT NULL REFERENCES locations(id),
    location_to_id BIGINT NOT NULL REFERENCES locations(id),
    movement_type VARCHAR(24) NOT NULL,
    reference_doc_type VARCHAR(40),
    reference_doc_id BIGINT,
    quantity NUMERIC(19, 4) NOT NULL,
    status VARCHAR(16) NOT NULL,
    created_by VARCHAR(120) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT ck_stock_ledger_quantity CHECK (quantity > 0)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(160) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    role VARCHAR(24) NOT NULL DEFAULT 'OPERATOR',
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE inventory_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_number VARCHAR(40) NOT NULL UNIQUE,
    document_type VARCHAR(24) NOT NULL,
    status VARCHAR(16) NOT NULL,
    note VARCHAR(500),
    created_by VARCHAR(120) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE inventory_document_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES inventory_documents(id),
    line_number INTEGER NOT NULL,
    product_id BIGINT NOT NULL REFERENCES products(id),
    location_from_id BIGINT REFERENCES locations(id),
    location_to_id BIGINT REFERENCES locations(id),
    quantity NUMERIC(19, 4) NOT NULL,
    CONSTRAINT uk_document_line_number UNIQUE (document_id, line_number),
    CONSTRAINT ck_document_line_quantity CHECK (quantity > 0)
);

CREATE TABLE password_reset_otps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    code_hash VARCHAR(100) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    consumed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX ix_products_category ON products(category_id);
CREATE INDEX ix_stock_ledger_product_created ON stock_ledger(product_id, created_at, id);
CREATE INDEX ix_stock_ledger_location_from ON stock_ledger(location_from_id);
CREATE INDEX ix_stock_ledger_location_to ON stock_ledger(location_to_id);
CREATE INDEX ix_locations_warehouse ON locations(warehouse_id);
CREATE INDEX ix_inventory_documents_type_created ON inventory_documents(document_type, created_at);
CREATE INDEX ix_inventory_documents_status_created ON inventory_documents(status, created_at);
CREATE INDEX ix_password_reset_otps_user ON password_reset_otps(user_id, created_at);

INSERT INTO locations (id, warehouse_id, name, code, is_internal, is_virtual, created_at) VALUES
    (1, NULL, 'Vendor', 'VENDOR', FALSE, TRUE, CURRENT_TIMESTAMP),
    (2, NULL, 'Customer', 'CUSTOMER', FALSE, TRUE, CURRENT_TIMESTAMP),
    (3, NULL, 'Inventory Adjustment', 'INVENTORY-ADJUSTMENT', FALSE, TRUE, CURRENT_TIMESTAMP);